// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCmx195MD2oXZrXTLcYyiseTluBCJLcXk',
    appId: '1:697091741834:web:7562de0a5623cbcc713573',
    messagingSenderId: '697091741834',
    projectId: 'dev-21c07',
    authDomain: 'dev-21c07.firebaseapp.com',
    databaseURL: 'https://dev-21c07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dev-21c07.appspot.com',
    measurementId: 'G-DD9V3J26ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0qXkyhUqRYjGtFfd5FN6a5NbkML81Cs',
    appId: '1:697091741834:android:99a12776c56ad9c0713573',
    messagingSenderId: '697091741834',
    projectId: 'dev-21c07',
    databaseURL: 'https://dev-21c07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dev-21c07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbH4gZ8HH8kDOVYW7C9mGXMgksIJixgDs',
    appId: '1:697091741834:ios:3da8c5edde49ea62713573',
    messagingSenderId: '697091741834',
    projectId: 'dev-21c07',
    databaseURL: 'https://dev-21c07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dev-21c07.appspot.com',
    iosBundleId: 'com.devsecure.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbH4gZ8HH8kDOVYW7C9mGXMgksIJixgDs',
    appId: '1:697091741834:ios:3da8c5edde49ea62713573',
    messagingSenderId: '697091741834',
    projectId: 'dev-21c07',
    databaseURL: 'https://dev-21c07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dev-21c07.appspot.com',
    iosBundleId: 'com.devsecure.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCmx195MD2oXZrXTLcYyiseTluBCJLcXk',
    appId: '1:697091741834:web:fca4ed598b406477713573',
    messagingSenderId: '697091741834',
    projectId: 'dev-21c07',
    authDomain: 'dev-21c07.firebaseapp.com',
    databaseURL: 'https://dev-21c07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dev-21c07.appspot.com',
    measurementId: 'G-E1LBKL3DM9',
  );
}
